version: '3.8'

services:
  db:
    image: postgres:15-alpine
    container_name: postgres_container
    restart: always
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "${DB_PORT}:${DB_PORT}"
    volumes:
      - pgdata:/var/lib/postgresql/data
      # Este mapeamento abaixo roda o seu script na primeira inicialização:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql

volumes:
  pgdata:
